version: '3.3'
services:
  db:
    container_name: db-mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - coding-net
  coding-challenge:
    image: coding-challenge
    build: .
    ports:
      - "8080:8080"
    networks:
      - coding-net
    depends_on:
      - db
    restart: on-failure

volumes:
  my-db:

networks:
  coding-net: