version: '3.2'
services:
  tradeshift:
    build: .
    container_name: "tradeshift"
    image: debian/latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:h2:mem:testdb
#    links:
#    depends_on:
#      - h2
#
#  h2:
#    container_name: 'h2'
#    hostname: 'h2'
#    image: 1000kit/h2
#    ports:
#      - "8181:8181"
#      - "1521:1521"
#    volumes:
#      - h2-data:/opt/h2-data
#  volumes:
#    h2-data:
  #END